version: '3.8'

services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  dev-app:
    build:
      context: .
    working_dir: /app
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
volumes:
  mongo-data:
