version: '3.8'

services:
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
  dev-app:
    build:
      context: .
    working_dir: /app
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - redis